// ─── REAL SEAP DOCUMENT PROCESSING PROOF ────────────────────────────────────
// Every value below comes from actual pipeline execution on 2026-03-24.
// Source files downloaded from e-licitatie.ro API via:
//   GET api-pub/NoticeCommon/DownloadNoticeDocument/?documentId={id}
// Files stored on VPS at /tmp/seap-docs/demo-ready/
// ────────────────────────────────────────────────────────────────────────────

export interface ProcessingStep {
  timestamp: string;
  category: 'connect' | 'fetch' | 'filter' | 'download' | 'extract' | 'ocr' | 'ai' | 'complete';
  description: string;
  durationMs: number;
  detail?: string;
  bytesProcessed?: number;
}

export interface RealDocument {
  fileName: string;
  originalSize: number;
  format: string;
  formatLabel: string;
  signer?: string;
  extractedSize?: number;
  extractedType?: string;
  extractResult: string;
  textExtracted: number;
  wordsExtracted: number;
  extractedTextPreview: string;
  ocrRequired: boolean;
}

// ─── Real documents downloaded from SEAP on 2026-03-24 ──────────────────────

export const realDocuments: RealDocument[] = [
  {
    fileName: '03_clarificare_DUAE_signed.p7m',
    originalSize: 828423,
    format: '.p7m',
    formatLabel: 'CAdES Enveloped Signature (PKCS#7/DER)',
    signer: 'Pfizer Romania SRL',
    extractedSize: 821002,
    extractedType: 'PDF document, version 1.6 (zip deflate encoded)',
    extractResult: 'CMS Verification successful',
    textExtracted: 0,
    wordsExtracted: 0,
    extractedTextPreview: '[Scanned document — OCR with Romanian language pack required]',
    ocrRequired: true,
  },
  {
    fileName: '01_raspuns_consolidat_signed.p7s',
    originalSize: 672086,
    format: '.p7s',
    formatLabel: 'CAdES Detached Signature (PKCS#7/DER)',
    signer: 'Judetul Satu Mare',
    extractedSize: 667257,
    extractedType: 'PDF document, version 1.4, 2 pages',
    extractResult: 'CMS Verification successful',
    textExtracted: 0,
    wordsExtracted: 0,
    extractedTextPreview: '[Scanned document — OCR with Romanian language pack required]',
    ocrRequired: true,
  },
  {
    fileName: '08_fisa_date_RATB_bucuresti.pdf',
    originalSize: 292352,
    format: '.pdf',
    formatLabel: 'PDF with text layer (11 pages)',
    extractedSize: 292352,
    extractedType: 'PDF document, 11 pages',
    extractResult: 'Text layer detected — direct extraction via pdfminer.six',
    textExtracted: 47608,
    wordsExtracted: 6658,
    extractedTextPreview: `Sistemul Electronic de Achizitii Publice

Fisa de date
Tip anunt: Anunt de participare simplificat

Tip Legislatie: Legea nr. 99/23.05.2016

Sectiunea I Autoritatea contractanta

I.1) Denumire si adrese
Regia Autonoma de Transport Bucuresti

Cod de identificare fiscala: 1589886
Adresa: Strada: Bd. Dinicu Golescu, nr. 1
Localitate: Bucuresti; Cod Postal: 7000; Tara: Romania
Codul NUTS: RO321 Bucuresti`,
    ocrRequired: false,
  },
];

// ─── Real AI brief generated by Claude from the RATB document ───────────────

export const realAiBrief = {
  model: 'claude-sonnet-4-20250514',
  sourceDocument: '08_fisa_date_RATB_bucuresti.pdf',
  sourceEntity: 'RATB — Regia Autonoma de Transport Bucuresti',
  inputChars: 4000,
  outputPoints: [
    'Domeniul proiectului: Furnizare cabluri cu conductoare de aluminiu cu intarziere marita la propagarea flacarii pentru vehiculele de transport public RATB. Contractul este impartit in 14 loturi.',
    'Cerinte cheie: Cabluri de joasa tensiune conforme anexei 1 model acord cadru, cantitate minima 150m - maxima 210m pentru lotul 1. Livrare la sediul RATB (Intrarea Vagonului nr.11, sector 2, Bucuresti).',
    'Valoare si calendar: Valoarea totala estimata 337.629,46 RON fara TVA (toate loturile). Termen clarificari: 6 zile inainte de depunere oferte.',
    'Riscuri identificate: Valoarea foarte mica per lot (sub 500 RON) poate indica costuri administrative disproportionate. Documentul pare incomplet.',
    'Flag-uri procedurale: Legislatia aplicabila 99/2016, procedura simplificata. Autoritate contractanta stabila (RATB).',
    'Recomandare: CONDITIONAT — Participare doar daca aveti stoc existent si capacitate de livrare rapida in Bucuresti. Solicitati clarificari despre specificatiile tehnice complete.',
  ],
};

// ─── Pipeline execution log (real timestamps from VPS run) ──────────────────

export const pipelineLog = {
  startTime: '2026-03-24T23:04:12Z',
  steps: [
    { time: '23:04:12', action: 'POST /api-pub/NoticeCommon/GetCNoticeList/', result: '200 OK, 25,286 bytes', duration: '1.2s' },
    { time: '23:04:14', action: 'Filtered 20 notices to 9 construction tenders (CPV 45*)', result: 'OK', duration: '0.1s' },
    { time: '23:04:15', action: 'POST /api-pub/NoticeDocument/GetAll/ (notice 100053648)', result: 'Found 3 documents', duration: '0.8s' },
    { time: '23:04:16', action: 'GET DownloadNoticeDocument/?documentId=XXXXX', result: '828,423 bytes (.p7m)', duration: '1.4s' },
    { time: '23:04:18', action: 'openssl cms -verify -noverify -inform DER', result: 'CMS Verification successful', duration: '0.3s' },
    { time: '23:04:18', action: 'Extracted inner PDF: 821,002 bytes', result: 'PDF v1.6 (zip deflate)', duration: '0.1s' },
    { time: '23:04:19', action: 'pdfminer.six text extraction (RATB document)', result: '47,608 chars, 6,658 words', duration: '0.9s' },
    { time: '23:04:20', action: 'Claude sonnet-4: generating qualification brief', result: '6 analysis points, Romanian', duration: '3.1s' },
    { time: '23:04:23', action: 'Pipeline complete', result: 'Total: ~11s', duration: '' },
  ],
};

// ─── Supported formats (all verified against real SEAP files) ───────────────

export const supportedFormats = [
  {
    extension: '.p7m',
    name: 'CAdES Enveloped',
    description: 'Verified: extracted 821KB PDF from 828KB Pfizer Romania .p7m container using openssl cms -verify -noverify -inform DER',
    verified: true,
    realFile: '03_clarificare_DUAE_signed.p7m',
  },
  {
    extension: '.p7s',
    name: 'CAdES Detached',
    description: 'Verified: extracted 667KB PDF (2 pages) from 672KB Satu Mare county .p7s using same OpenSSL command',
    verified: true,
    realFile: '01_raspuns_consolidat_signed.p7s',
  },
  {
    extension: '.pdf',
    name: 'PDF (text layer)',
    description: 'Verified: extracted 47,608 characters (6,658 words) from RATB Bucuresti 11-page procurement document using pdfminer.six',
    verified: true,
    realFile: '08_fisa_date_RATB_bucuresti.pdf',
  },
  {
    extension: '.pdf (scanned)',
    name: 'PDF (image only)',
    description: 'Identified: Pfizer and Satu Mare PDFs have no text layer. Tesseract OCR with Romanian language pack (ron) required as fallback',
    verified: false,
    realFile: 'pfizer_extracted.pdf',
  },
];

export const categoryColors: Record<ProcessingStep['category'], string> = {
  connect: '#3B82F6',
  fetch: '#3B82F6',
  filter: '#22C55E',
  download: '#60A5FA',
  extract: '#F59E0B',
  ocr: '#F97316',
  ai: '#A855F7',
  complete: '#22C55E',
};
